// Hand-authored content for the v0.2 mock product (Larkspur). See docs/data-model-v2.md.
// generate.mjs turns this into prototypes/shared/v2/blueprint-data.js; nothing here is random.
//
// Features are [name, summary, surfaces]. Surface codes: w web storefront, a admin, m mobile app,
// p api, k worker, d data. A module's surfaces are the union of its features' surfaces.
// A module may set `since`: the first release any of its features can ship in.

export const product = {
  id: 'larkspur',
  name: 'Larkspur',
  tagline: 'Commerce platform for independent brands',
  version: '1.11.3',
  nextVersion: '1.12.0',
  stack: {
    web: 'Next.js storefront and admin · React Native app',
    api: 'Node.js · GraphQL and REST',
    workers: 'Node.js workers on BullMQ',
    data: 'Postgres · Redis · ClickHouse warehouse',
    infra: 'AWS ECS · Terraform · CloudFront',
  },
};

export const areas = [
  { id: 'shopper', name: 'Shopper Experience', summary: 'Everything a shopper sees and touches, from browsing and search to reviews and the mobile app.' },
  { id: 'commerce', name: 'Commerce Core', summary: 'The money path: carts, checkout, payments, pricing and subscription billing.' },
  { id: 'fulfillment', name: 'Fulfillment & Service', summary: 'What happens after the order: order handling, stock, shipping and customer care.' },
  { id: 'merchant', name: 'Merchant Platform', summary: 'The tools merchants use to run their store: the admin, analytics and integrations.' },
  { id: 'foundation', name: 'Foundation', summary: 'Shared identity, infrastructure and data services that every other area builds on.' },
];

export const domains = [
  { id: 'storefront', areaId: 'shopper', code: 'STF', name: 'Storefront', summary: 'The shopper-facing store: catalog data, product pages, content and the theme system.' },
  { id: 'discovery', areaId: 'shopper', code: 'DSC', name: 'Search & Discovery', summary: 'Helps shoppers find products through search, recommendations and merchandised collections.' },
  { id: 'community', areaId: 'shopper', code: 'CMY', name: 'Community', summary: 'Reviews, questions and loyalty programs that turn shoppers into repeat customers.' },
  { id: 'mobile', areaId: 'shopper', code: 'MOB', name: 'Mobile App', summary: 'The native shopping app for iOS and Android, built on the shared commerce APIs.' },
  { id: 'checkout', areaId: 'commerce', code: 'CHK', name: 'Cart & Checkout', summary: 'Turns intent into orders: the cart, the checkout flow and one-tap express options.' },
  { id: 'payments', areaId: 'commerce', code: 'PAY', name: 'Payments', summary: 'Card and alternative payment processing, fraud screening and merchant payouts.' },
  { id: 'pricing', areaId: 'commerce', code: 'PRC', name: 'Pricing & Promotions', summary: 'Price lists, discounts and gift cards across markets and currencies.' },
  { id: 'billing', areaId: 'commerce', code: 'BIL', name: 'Subscriptions & Billing', summary: 'Recurring orders for shoppers, and plan billing, invoices and tax for merchants.' },
  { id: 'orders', areaId: 'fulfillment', code: 'ORD', name: 'Order Management', summary: 'The life of an order from placement to completion, including edits, returns and exchanges.' },
  { id: 'inventory', areaId: 'fulfillment', code: 'INV', name: 'Inventory', summary: 'Stock levels across locations, purchase orders from suppliers and demand forecasts.' },
  { id: 'shipping', areaId: 'fulfillment', code: 'SHP', name: 'Shipping & Delivery', summary: 'Carrier rates, labels, tracking and local delivery for every order.' },
  { id: 'care', areaId: 'fulfillment', code: 'CAR', name: 'Customer Care', summary: 'Self-service help, the support inbox and the messages shoppers receive.' },
  { id: 'admin', areaId: 'merchant', code: 'ADM', name: 'Admin & Operations', summary: 'The merchant admin: daily operations, bulk tools, staff accounts and permissions.' },
  { id: 'analytics', areaId: 'merchant', code: 'ANL', name: 'Analytics', summary: 'Event collection, standard reports and insights that explain store performance.' },
  { id: 'integrations', areaId: 'merchant', code: 'INT', name: 'Integrations', summary: 'The public API, webhooks, sales channels and the app store for third-party extensions.' },
  { id: 'identity', areaId: 'foundation', code: 'IAM', name: 'Identity & Access', summary: 'Sign-in, customer accounts, privacy controls and sessions for shoppers and staff.' },
  { id: 'platform', areaId: 'foundation', code: 'PLT', name: 'Platform & Reliability', summary: 'The infrastructure, observability and data platform that keep Larkspur running.' },
];

export const modules = [
  // ── Storefront ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'catalog', domainId: 'storefront', name: 'Product Catalog', owner: 'shopper',
    summary: 'Products, variants, collections and the media that describe them.',
    features: [
      ['Product records', 'Create and edit products with titles, descriptions, SEO fields and status in one form.', 'ap'],
      ['Variant matrix', 'Generate size, color and material variants, each with its own SKU, price and stock.', 'ap'],
      ['Product media library', 'Upload images and video once and reuse them across products and variants.', 'apk'],
      ['Image optimization', 'Resize, crop and convert product images to WebP and AVIF on upload.', 'k'],
      ['Manual collections', 'Hand-pick products into collections and order them with drag and drop.', 'a'],
      ['Smart collections', 'Build collections from rules such as tag, vendor, price or stock level.', 'ak'],
      ['Product tags and types', 'Classify products with tags and product types that filters and rules can use.', 'ap'],
      ['Metafields', 'Add custom typed fields to products for specs, care instructions and badges.', 'ap'],
      ['Catalog CSV import', 'Import thousands of products from a spreadsheet with a dry run and an error report.', 'ak'],
      ['Catalog API', 'Read and write products, variants and collections through versioned REST endpoints.', 'p'],
      ['Product drafts and scheduling', 'Keep products in draft and publish them automatically at a scheduled time.', 'ak'],
      ['Archived products', 'Retire products without deleting their order history or breaking old links.', 'aw'],
      ['Catalog translations', 'Translate titles, descriptions and option names for each storefront language.', 'ap'],
    ],
  },
  {
    id: 'product-pages', domainId: 'storefront', name: 'Product Pages', owner: 'shopper',
    summary: 'The product detail page shoppers use to choose, compare and add to cart.',
    features: [
      ['Product detail page', 'Responsive product page with gallery, variant picker, price and add to cart.', 'wm'],
      ['Variant picker', 'Swatches and dropdowns that update price, image and stock as options change.', 'w'],
      ['Image zoom and gallery', 'Pinch, zoom and swipe through product media, including 360 spins and video.', 'w'],
      ['Stock messaging', 'Show low-stock notes, restock dates and per-store availability on the page.', 'wp'],
      ['Back-in-stock alerts', 'Let shoppers ask for an email or SMS when a sold-out variant returns.', 'wk'],
      ['Size guides', 'Attach size charts and fit notes to products and show them in a dialog.', 'wa'],
      ['Product bundles', 'Sell fixed bundles of products at one price, with stock tracked per item.', 'wa'],
      ['Complete the look', 'Show items styled with the current product, curated by merchandisers.', 'wa'],
      ['Recently viewed', 'Remember the last products a shopper looked at across visits.', 'w'],
      ['Delivery estimate', "Show an estimated delivery date for the shopper's postcode before checkout.", 'wp'],
      ['Product page SEO', 'Structured data, canonical URLs and meta tags generated for every product.', 'w'],
      ['Pre-orders', 'Take orders for upcoming products with a clear ship date and an optional deposit.', 'wa'],
    ],
  },
  {
    id: 'content', domainId: 'storefront', name: 'Content & Pages', owner: 'shopper',
    summary: "Pages, blog posts and navigation that tell each brand's story.",
    features: [
      ['Page builder', 'Compose landing pages from sections such as hero, grid and story, without code.', 'wa'],
      ['Blog', 'Publish articles with authors, tags and featured products.', 'wa'],
      ['Navigation menus', 'Build header and footer menus with nested links and mega-menu columns.', 'wa'],
      ['Content scheduling', 'Schedule pages and banners to go live and expire automatically.', 'ak'],
      ['Announcement bar', 'Show a dismissible store-wide message for sales, shipping or news.', 'wa'],
      ['Store policies', 'Host refund, privacy and terms pages from templates, with version history.', 'wa'],
      ['URL redirects', 'Manage permanent redirects in bulk so old links and search rankings keep working.', 'ap'],
      ['Content localization', 'Translate pages, menus and blog posts per market, with fallbacks.', 'wap'],
      ['Headless content API', 'Deliver pages and content blocks as JSON for custom front ends.', 'p'],
    ],
  },
  {
    id: 'themes', domainId: 'storefront', name: 'Themes & Branding', owner: 'shopper',
    summary: 'The theme system that gives each brand its own look on the web and in email.',
    features: [
      ['Theme editor', 'Change colors, fonts and sections with a live preview of the storefront.', 'wa'],
      ['Theme library', 'Pick from a set of starter themes and install one in a single click.', 'wa'],
      ['Brand kit', 'Store logos, colors and fonts once and apply them to the store, email and receipts.', 'a'],
      ['Theme versions', 'Keep theme drafts, compare versions and roll back a published theme.', 'a'],
      ['Custom fonts', 'Upload brand fonts with subsetting and sensible fallback stacks.', 'wa'],
      ['Theme code editor', 'Edit theme templates and styles directly, with linting and a diff view.', 'a'],
      ['Dark mode storefront', 'Let shoppers switch the storefront to a dark palette defined by the theme.', 'w'],
      ['Email templates', 'Brand transactional emails with the same design tokens as the storefront.', 'ak'],
      ['Theme performance budget', 'Warn when a theme change pushes page weight or script time over budget.', 'ak'],
    ],
  },
  // ── Search & Discovery ──────────────────────────────────────────────────────────────────────
  {
    id: 'search', domainId: 'discovery', name: 'Search', owner: 'shopper',
    summary: 'Fast, typo-tolerant product search across the storefront, the app and custom front ends.',
    features: [
      ['Product search', 'Full-text search over titles, descriptions, tags and SKUs with relevance ranking.', 'wmp'],
      ['Autocomplete', 'Suggest products, collections and popular queries as the shopper types.', 'wmp'],
      ['Typo tolerance', 'Return good results for misspelled and partial queries.', 'p'],
      ['Faceted filters', 'Filter results by size, color, price, brand and stock, with live counts.', 'wm'],
      ['Synonyms', 'Map words such as sneakers and trainers so they return the same products.', 'ap'],
      ['Search index pipeline', 'Keep the search index in sync with catalog, price and stock changes within seconds.', 'k'],
      ['Zero-result recovery', 'Suggest related queries and best sellers when a search finds nothing.', 'w'],
      ['Search analytics', 'Show merchants their top queries, zero-result queries and click-through rates.', 'ad'],
      ['Pinned results', 'Pin or bury specific products for chosen queries.', 'a'],
      ['Multilingual search', 'Search each storefront language with its own stemming and stop words.', 'p'],
      ['Visual search', 'Find similar products from a photo the shopper uploads.', 'wm'],
      ['Search API', 'Query the search service from custom front ends and partner apps.', 'p'],
    ],
  },
  {
    id: 'recommendations', domainId: 'discovery', name: 'Recommendations', owner: 'shopper', since: '1.7',
    summary: 'Personalized product suggestions on pages, in the cart and in email.',
    features: [
      ['Related products', 'Show products that are often viewed together on each product page.', 'wk'],
      ['Frequently bought together', 'Suggest add-ons bought with the current product, ready to add in one tap.', 'wk'],
      ['Personalized home feed', "Order home page products by each shopper's browsing and purchases.", 'wmk'],
      ['Trending now', 'Highlight products with rising views and sales over the last 24 hours.', 'wk'],
      ['Cart recommendations', 'Recommend low-cost add-ons in the cart to lift order value.', 'wk'],
      ['Recommendation emails', 'Send personalized picks in post-purchase and win-back emails.', 'k'],
      ['Model training jobs', 'Retrain recommendation models nightly on fresh orders and events.', 'kd'],
      ['Recommendation rules', 'Let merchants exclude products or boost a collection in recommendations.', 'a'],
    ],
  },
  {
    id: 'merchandising', domainId: 'discovery', name: 'Merchandising', owner: 'shopper',
    summary: 'Tools that let merchants shape how collections and search results are ordered.',
    features: [
      ['Collection sorting rules', 'Sort collections by best selling, newest, margin or a manual order.', 'a'],
      ['Visual merchandiser', 'Drag products on a grid preview of a collection page to reorder them.', 'a'],
      ['Product badges', 'Add New, Low stock or custom badges to product cards by rule.', 'wa'],
      ['Campaign landing pages', 'Launch a sale page with its own collection, banner and countdown.', 'wa'],
      ['Out-of-stock demotion', 'Push sold-out products to the end of collections automatically.', 'k'],
      ['Merchandising A/B tests', 'Test two collection orders and keep the one that sells more.', 'ad'],
      ['Seasonal collections', 'Prepare holiday collections ahead of time and switch them on by date.', 'ak'],
      ['Cross-sell slots', 'Reserve slots in product grids for promoted collections or editorial cards.', 'wa'],
      ['Margin-aware ranking', 'Weight rankings by margin so profitable products surface first.', 'k'],
    ],
  },
  // ── Community ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'reviews', domainId: 'community', name: 'Reviews & Ratings', owner: 'shopper', since: '1.6',
    summary: 'Verified product reviews and star ratings that build shopper trust.',
    features: [
      ['Product reviews', 'Let shoppers write reviews with star ratings, titles and fit feedback.', 'wm'],
      ['Review request emails', 'Ask buyers for a review a set number of days after delivery.', 'k'],
      ['Verified buyer badges', 'Mark reviews written by confirmed purchasers.', 'w'],
      ['Photo and video reviews', 'Accept photo and video uploads with reviews, after moderation.', 'wm'],
      ['Review moderation', 'Approve, reject or flag reviews, with automatic spam and profanity filters.', 'ak'],
      ['Merchant replies', 'Let merchants answer reviews publicly from the admin.', 'a'],
      ['Rating summary widget', 'Show the average rating and its distribution on product and collection pages.', 'w'],
      ['Review syndication', 'Share reviews across sister stores and marketplace listings.', 'pk'],
      ['Review incentives', 'Reward reviewers with points or a discount without biasing ratings.', 'ak'],
    ],
  },
  {
    id: 'ugc', domainId: 'community', name: 'Q&A and UGC', owner: 'shopper', since: '1.12',
    summary: 'Shopper questions, answers and photos that fill product pages with real voices.',
    features: [
      ['Product Q&A', 'Let shoppers ask questions on product pages and get answers from staff or buyers.', 'wm'],
      ['Answer notifications', 'Email the person who asked when their question gets an answer.', 'k'],
      ['Shoppable social gallery', 'Show tagged customer photos with links to the products in them.', 'wa'],
      ['UGC rights requests', 'Ask creators for permission before reusing their photos.', 'ak'],
      ['Community moderation queue', 'Review flagged questions, answers and photos in one queue.', 'a'],
      ['Q&A search', 'Search existing questions before asking a new one.', 'w'],
      ['Creator profiles', 'Public profiles for top contributors, with their reviews and photos.', 'wm'],
    ],
  },
  {
    id: 'loyalty', domainId: 'community', name: 'Loyalty & Referrals', owner: 'shopper', since: '1.7',
    summary: 'Points, tiers and referral rewards that bring shoppers back.',
    features: [
      ['Points program', 'Earn points on orders, reviews and birthdays, and spend them at checkout.', 'wmp'],
      ['Loyalty tiers', 'Unlock perks such as free shipping when shoppers reach spending tiers.', 'wa'],
      ['Referral links', 'Give shoppers a personal link that rewards both the friend and the referrer.', 'wm'],
      ['Rewards catalog', 'Let shoppers redeem points for discounts, products or donations.', 'wm'],
      ['Points ledger', 'Keep an auditable balance of points earned, spent and expired.', 'pd'],
      ['Points expiry', 'Expire unused points on a schedule, with reminder emails beforehand.', 'k'],
      ['Loyalty admin', 'Configure earning rules, tiers and rewards from the admin.', 'a'],
      ['Referral fraud checks', 'Block self-referrals and reward farming with device and address checks.', 'k'],
      ['Member-only pricing', 'Show special prices to signed-in loyalty members.', 'wp'],
    ],
  },
  // ── Mobile App ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'app-shell', domainId: 'mobile', name: 'App Shell', owner: 'shopper', since: '1.10',
    summary: 'The native app frame: navigation, sign-in, push messages and offline behavior.',
    features: [
      ['Native app navigation', 'Tab bar, deep links and gestures shared by the iOS and Android apps.', 'm'],
      ['App sign-in', 'Sign in with email, a passkey, or Apple and Google accounts in the app.', 'mp'],
      ['Push notifications', 'Send order updates and campaigns as push messages, with opt-in control.', 'mk'],
      ['Offline browsing', 'Browse recently loaded products and the cart without a connection.', 'm'],
      ['Deep linking', 'Open products, collections and orders in the app from links and emails.', 'mp'],
      ['App theming', "Apply the store's brand kit to the app's colors, fonts and icons.", 'ma'],
      ['Over-the-air updates', 'Ship content and layout updates without an app store release.', 'mk'],
      ['Crash reporting', 'Collect crash reports and app performance traces for each release.', 'md'],
      ['App store publishing', "Build, sign and submit each brand's app to the app stores.", 'ak'],
    ],
  },
  {
    id: 'mobile-checkout', domainId: 'mobile', name: 'Mobile Checkout', owner: 'shopper', since: '1.11',
    summary: 'Checkout built for thumbs, with native wallets and one-tap reorders.',
    features: [
      ['Native checkout', 'A native checkout flow with saved addresses and payment methods.', 'mp'],
      ['Apple Pay in app', 'Pay with Apple Pay inside the iOS app with a single confirmation.', 'mp'],
      ['Google Pay in app', 'Pay with Google Pay inside the Android app.', 'mp'],
      ['One-tap reorder', 'Repeat a past order from the order history in one tap.', 'm'],
      ['Mobile cart sync', 'Keep the cart in sync between the app and the website for signed-in shoppers.', 'mp'],
      ['Biometric confirmation', 'Confirm payments with Face ID or a fingerprint.', 'm'],
      ['In-app order tracking', "Follow an order's journey on a live map inside the app.", 'm'],
    ],
  },
  {
    id: 'app-engagement', domainId: 'mobile', name: 'App Engagement', owner: 'shopper', since: '1.11',
    summary: 'Wishlists, stories and offers that keep app users coming back.',
    features: [
      ['Wishlists', 'Save products to named wishlists and share them with friends.', 'wmp'],
      ['Price drop alerts', 'Notify shoppers when a wishlisted product goes on sale.', 'mk'],
      ['Shoppable stories', 'Swipeable brand stories with tagged products.', 'ma'],
      ['App-only offers', 'Exclusive discounts that only apply to orders placed in the app.', 'ma'],
      ['In-app inbox', 'A message center for offers, order news and loyalty updates.', 'm'],
      ['Home screen widgets', 'iOS and Android widgets for order status and new arrivals.', 'm'],
      ['Engagement analytics', 'Track app opens, retention and push conversion per campaign.', 'ad'],
      ['Gamified challenges', 'Reward streaks and challenges with loyalty points.', 'm'],
    ],
  },
  // ── Cart & Checkout ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cart', domainId: 'checkout', name: 'Cart', owner: 'checkout',
    summary: 'The shopping cart: adding, editing and saving items before checkout.',
    features: [
      ['Cart drawer', 'Slide-out cart with line items, quantity steppers and a running subtotal.', 'w'],
      ['Persistent carts', 'Keep carts across devices and visits for signed-in shoppers.', 'wp'],
      ['Cart API', 'Create and update carts from any front end or app.', 'p'],
      ['Save for later', 'Move items out of the cart into a saved list without losing them.', 'wm'],
      ['Free shipping meter', 'Show how much more the shopper needs to spend for free shipping.', 'w'],
      ['Cart line properties', 'Capture engraving text, gift notes and other custom fields on each line.', 'wp'],
      ['Abandoned cart emails', 'Remind shoppers about items left in their cart, with a link back.', 'k'],
      ['Stock reservation', 'Hold stock for items in an active checkout for a few minutes.', 'pk'],
      ['Cart price recalculation', 'Recalculate prices, discounts and tax whenever the cart changes.', 'p'],
      ['Shareable carts', 'Share a prefilled cart link, for example from a stylist or a creator.', 'wp'],
    ],
  },
  {
    id: 'checkout-flow', domainId: 'checkout', name: 'Checkout Flow', owner: 'checkout',
    summary: 'The steps from cart to order confirmation, including tax, shipping and discounts.',
    features: [
      ['One-page checkout', 'Contact, shipping and payment on one page, with inline validation.', 'wm'],
      ['Guest checkout', 'Buy without an account, with an option to save details afterwards.', 'w'],
      ['Address autocomplete', 'Suggest verified addresses as the shopper types to cut delivery errors.', 'wp'],
      ['Shipping method picker', 'Show rates and delivery dates for each shipping option.', 'wp'],
      ['Tax at checkout', 'Calculate sales tax and VAT for the destination in real time.', 'p'],
      ['Discount code field', 'Apply and validate discount codes with clear error messages.', 'wp'],
      ['Order confirmation page', 'Thank-you page with the order summary, a tracking link and an account prompt.', 'w'],
      ['Checkout extensibility', 'Let apps add fields and blocks to checkout without forking it.', 'wp'],
      ['Multi-currency checkout', 'Charge shoppers in their local currency with locked exchange rates.', 'wp'],
      ['Checkout error recovery', 'Keep entered details and retry gracefully after payment or network errors.', 'w'],
      ['Order notes', 'Let shoppers add delivery instructions and gift notes to the order.', 'w'],
      ['Checkout accessibility', 'Keyboard, screen reader and zoom support across every checkout step.', 'w'],
    ],
  },
  {
    id: 'express', domainId: 'checkout', name: 'Express Checkout', owner: 'checkout',
    summary: 'Accelerated wallet and one-click buttons that skip the checkout form.',
    features: [
      ['Express pay buttons', 'Show wallet buttons on product, cart and checkout pages.', 'w'],
      ['Apple Pay on web', 'Pay with Apple Pay in Safari, choosing shipping inside the payment sheet.', 'wp'],
      ['Google Pay on web', 'Pay with Google Pay in supported browsers.', 'wp'],
      ['PayPal checkout', 'Hand off to PayPal and return with the address and payment approved.', 'wp'],
      ['Buy now button', 'Skip the cart and go straight to a prefilled checkout.', 'w'],
      ['Saved checkout profiles', "Remember a returning shopper's details for one-click checkout.", 'wp'],
      ['Express shipping defaults', 'Pick the cheapest valid rate automatically inside wallet sheets.', 'p'],
    ],
  },
  // ── Payments ────────────────────────────────────────────────────────────────────────────────
  {
    id: 'cards', domainId: 'payments', name: 'Card Processing', owner: 'payments',
    summary: 'Accepting card payments securely in every market.',
    features: [
      ['Card payments', 'Authorize and capture Visa, Mastercard and Amex payments.', 'p'],
      ['Hosted card fields', 'Collect card details in isolated fields so card data never touches the store.', 'w'],
      ['3-D Secure', 'Run strong customer authentication challenges when the issuer requires them.', 'wp'],
      ['Card vault tokens', 'Store cards as network tokens for repeat and subscription payments.', 'p'],
      ['Card updater', 'Refresh expired or reissued cards automatically before they fail.', 'k'],
      ['Partial captures', 'Capture part of an authorization as items ship.', 'ap'],
      ['Refunds to card', 'Refund all or part of a card payment from the admin or the API.', 'ap'],
      ['Authorization retries', 'Retry soft-declined authorizations with smart timing.', 'k'],
      ['Payment method display', 'Show the card brand and last four digits on orders and receipts.', 'wa'],
      ['Multi-acquirer routing', 'Route each transaction to the acquirer with the best approval rate.', 'pk'],
      ['Dispute evidence', 'Gather and submit chargeback evidence from order and shipping data.', 'ak'],
      ['Card BIN lookup', 'Identify card type, issuer country and funding source before authorizing.', 'p'],
    ],
  },
  {
    id: 'alt-payments', domainId: 'payments', name: 'Alternative Payments', owner: 'payments',
    summary: 'Wallets, bank payments and pay-later options beyond cards.',
    features: [
      ['Buy now, pay later', 'Offer instalment plans from pay-later providers at checkout.', 'wp'],
      ['iDEAL payments', 'Accept bank payments in the Netherlands through iDEAL.', 'wp'],
      ['SEPA Direct Debit', 'Collect euro payments by direct debit, with mandate management.', 'wpk'],
      ['Bank transfer payments', 'Show bank details and match incoming transfers to orders.', 'wk'],
      ['Local wallets', 'Accept popular regional wallets in Asia and Latin America.', 'wp'],
      ['Cash on delivery', 'Let shoppers pay the courier, with reconciliation per shipment.', 'wa'],
      ['Payment method rules', 'Show or hide payment methods by country, order value or product.', 'a'],
      ['Pay by link', 'Send a payment link by email or chat for phone and social orders.', 'ap'],
      ['Open banking payments', 'Pay directly from a bank account with instant confirmation.', 'wp'],
      ['Stablecoin payments', 'Accept stablecoin payments, settled to the merchant in local currency.', 'wp'],
    ],
  },
  {
    id: 'risk', domainId: 'payments', name: 'Fraud & Risk', owner: 'payments',
    summary: 'Stopping fraud and abuse before they cost merchants money.',
    features: [
      ['Fraud scoring', 'Score every order for fraud risk using device, address and payment signals.', 'k'],
      ['Risk review queue', 'Let merchants approve or cancel orders flagged as risky.', 'a'],
      ['Velocity rules', 'Block bursts of attempts from one card, device or address.', 'k'],
      ['Address verification', "Compare billing address and postcode with the card issuer's records.", 'p'],
      ['Chargeback alerts', 'Get early warning of disputes so orders can be refunded first.', 'k'],
      ['Block lists', 'Block emails, cards, IP addresses and street addresses known for fraud.', 'a'],
      ['Account takeover detection', 'Spot unusual sign-ins before a stolen account places orders.', 'k'],
      ['Fraud model retraining', 'Retrain the fraud model weekly on confirmed fraud and chargebacks.', 'kd'],
      ['Risk insights', 'Show merchants fraud rate, dispute and approval rate trends.', 'ad'],
      ['Card testing defense', 'Detect and stop bots that test stolen cards with small payments.', 'k'],
    ],
  },
  {
    id: 'payouts', domainId: 'payments', name: 'Payouts & Reconciliation', owner: 'payments',
    summary: 'Getting money to merchants and proving every cent adds up.',
    features: [
      ['Merchant payouts', 'Pay out merchant balances on a daily, weekly or monthly schedule.', 'ak'],
      ['Payout reports', 'Break each payout down into orders, refunds, fees and adjustments.', 'ad'],
      ['Balance ledger', 'Track every movement of merchant funds with double-entry records.', 'd'],
      ['Bank reconciliation', 'Match payouts to bank statement lines automatically.', 'k'],
      ['Instant payouts', 'Let merchants withdraw funds to a debit card within minutes.', 'a'],
      ['Multi-currency balances', 'Hold balances in several currencies and convert at payout time.', 'kd'],
      ['Payout holds', 'Hold payouts for accounts under risk review, with a clear reason.', 'ak'],
      ['Fee invoices', 'Generate monthly invoices for processing fees.', 'k'],
      ['Settlement file import', 'Import acquirer settlement files and flag mismatches.', 'k'],
    ],
  },
  // ── Pricing & Promotions ────────────────────────────────────────────────────────────────────
  {
    id: 'prices', domainId: 'pricing', name: 'Price Management', owner: 'checkout',
    summary: 'List prices, compare-at prices and market-specific pricing.',
    features: [
      ['Price lists', 'Maintain separate price lists for retail, wholesale and VIP customers.', 'ap'],
      ['Market pricing', 'Set prices per country or currency instead of converting automatically.', 'ap'],
      ['Compare-at prices', 'Show the original price struck through next to a sale price.', 'wa'],
      ['Bulk price editor', 'Change prices across many products by a percentage or a fixed amount.', 'a'],
      ['Price rounding rules', 'Round converted prices to endings such as .99 or .95.', 'p'],
      ['Scheduled price changes', 'Schedule price updates to start and end at set times.', 'ak'],
      ['Price history', 'Keep a dated history of every price change for audits and EU pricing rules.', 'ad'],
      ['B2B tiered pricing', 'Volume price breaks for wholesale customers.', 'wp'],
    ],
  },
  {
    id: 'discounts', domainId: 'pricing', name: 'Discounts', owner: 'checkout',
    summary: 'Codes, automatic discounts and promotions with clear stacking rules.',
    features: [
      ['Discount codes', 'Create percentage, fixed and free-shipping codes with usage limits.', 'ap'],
      ['Automatic discounts', 'Apply discounts without a code when cart conditions are met.', 'p'],
      ['Buy X get Y', 'Run buy-one-get-one and multi-buy promotions.', 'ap'],
      ['Bulk code generation', 'Generate thousands of unique single-use codes for a campaign.', 'ak'],
      ['Discount stacking rules', 'Decide which discounts combine and which one wins.', 'ap'],
      ['Tiered spend discounts', 'Give bigger discounts at higher cart totals.', 'ap'],
      ['First-order discount', 'Welcome new subscribers with a one-time code.', 'ak'],
      ['Discount analytics', 'See revenue, orders and margin impact for each discount.', 'ad'],
      ['Customer-segment discounts', 'Limit a discount to a customer segment or a loyalty tier.', 'ap'],
      ['Flash sale scheduler', 'Start and stop store-wide sales at exact times across time zones.', 'ak'],
      ['Discount abuse checks', 'Catch codes leaked to coupon sites and repeated use by one shopper.', 'k'],
    ],
  },
  {
    id: 'gift-cards', domainId: 'pricing', name: 'Gift Cards', owner: 'checkout',
    summary: 'Digital and physical gift cards, sold as products and accepted as payment.',
    features: [
      ['Digital gift cards', 'Sell gift cards delivered by email on a chosen date.', 'wk'],
      ['Gift card redemption', 'Pay with a gift card balance at checkout, alone or with another method.', 'wp'],
      ['Gift card balance check', "Let shoppers check a card's remaining balance online.", 'w'],
      ['Physical gift cards', 'Issue and activate printed cards sold in shops.', 'ap'],
      ['Gift card issuing', 'Issue cards manually for refunds, goodwill or promotions.', 'a'],
      ['Gift card liability report', 'Report outstanding gift card balances for accounting.', 'ad'],
      ['Gift card expiry rules', 'Apply expiry rules that respect local consumer law.', 'k'],
    ],
  },
  // ── Subscriptions & Billing ─────────────────────────────────────────────────────────────────
  {
    id: 'subscriptions', domainId: 'billing', name: 'Subscriptions', owner: 'payments', since: '1.5',
    summary: 'Recurring product orders that shoppers can manage on their own.',
    features: [
      ['Subscribe and save', 'Offer a discount for subscribing to repeat deliveries.', 'wp'],
      ['Subscription plans', 'Configure delivery frequencies, discounts and minimum cycles.', 'a'],
      ['Customer subscription portal', 'Let shoppers skip, pause, swap or cancel their subscription.', 'wm'],
      ['Renewal billing', 'Charge renewals on schedule, with retries for failed payments.', 'k'],
      ['Dunning emails', 'Remind shoppers to update payment details after a failed renewal.', 'k'],
      ['Prepaid subscriptions', 'Sell multi-month plans paid up front, with deliveries spread out.', 'wa'],
      ['Subscription box builder', 'Let shoppers pick the items in each box from a curated set.', 'w'],
      ['Cancellation flow', 'Offer pause or discount options before a shopper cancels.', 'w'],
      ['Subscription analytics', 'Track active subscribers, churn and recurring revenue.', 'ad'],
      ['Subscription API', 'Manage subscriptions from custom front ends and apps.', 'p'],
      ['Gifted subscriptions', 'Buy a subscription for someone else, with a gift message.', 'w'],
    ],
  },
  {
    id: 'merchant-billing', domainId: 'billing', name: 'Merchant Billing', owner: 'payments',
    summary: 'Plans, usage charges and invoices for Larkspur merchants.',
    features: [
      ['Plan selection', 'Let merchants choose and change their Larkspur plan.', 'a'],
      ['Usage-based charges', 'Bill transaction fees and add-on usage on top of the plan price.', 'k'],
      ['Merchant invoices', 'Monthly invoices with line items, credits and taxes.', 'ak'],
      ['Billing payment methods', 'Keep a card or direct debit on file for the merchant account.', 'a'],
      ['Trial management', 'Run free trials with reminders before the first charge.', 'ak'],
      ['Plan entitlements', "Turn features on or off according to the merchant's plan.", 'p'],
      ['Billing alerts', 'Warn merchants before a failed charge suspends their store.', 'k'],
      ['Partner revenue share', 'Calculate and pay revenue share to agencies and app partners.', 'kd'],
    ],
  },
  {
    id: 'invoicing', domainId: 'billing', name: 'Invoicing & Tax', owner: 'payments',
    summary: 'Customer invoices and the tax engine behind every price.',
    features: [
      ['Tax engine', 'Work out sales tax, VAT and GST for every order line by destination.', 'p'],
      ['Tax-inclusive pricing', 'Show prices with tax included in markets that expect it.', 'wp'],
      ['Customer invoices', 'Generate numbered invoices and credit notes as PDF for each order.', 'ak'],
      ['EU VAT OSS reports', 'Prepare one-stop-shop VAT returns for EU distance sales.', 'ad'],
      ['Tax exemptions', 'Store exemption certificates for wholesale customers and skip tax.', 'ap'],
      ['US sales tax nexus', 'Track sales per state and warn when a nexus threshold is near.', 'ad'],
      ['E-invoicing', 'Send invoices in structured formats where the law requires them.', 'k'],
      ['Tax rate updates', 'Load new tax rates automatically before they take effect.', 'k'],
      ['Duties at checkout', 'Estimate import duties for cross-border orders and collect them up front.', 'wp'],
    ],
  },
  // ── Order Management ────────────────────────────────────────────────────────────────────────
  {
    id: 'order-lifecycle', domainId: 'orders', name: 'Order Lifecycle', owner: 'fulfillment',
    summary: 'Every order from placement to completion.',
    features: [
      ['Order timeline', 'Show every event on an order, from payment to delivery, in one timeline.', 'a'],
      ['Order list and filters', 'Find orders by status, date, channel, tag or customer.', 'a'],
      ['Order status page', 'Let shoppers see order status and tracking without signing in.', 'w'],
      ['Fulfillment requests', 'Send orders to warehouses or logistics partners, with split shipments.', 'pk'],
      ['Order tags', 'Tag orders automatically by rule for routing and reporting.', 'ak'],
      ['Order API', 'Read and update orders from integrations and apps.', 'p'],
      ['Order archiving', 'Archive completed orders and keep them searchable.', 'ak'],
      ['Draft orders', 'Create orders for phone and email sales and send an invoice to pay.', 'a'],
      ['Order risk holds', 'Hold fulfillment until a risky order has been reviewed.', 'k'],
      ['Order export', 'Export orders to CSV with line items, taxes and discounts.', 'ak'],
      ['Partial fulfillment', 'Ship what is in stock now and send the rest later.', 'ak'],
    ],
  },
  {
    id: 'order-editing', domainId: 'orders', name: 'Order Editing', owner: 'fulfillment',
    summary: 'Changing orders after they are placed, with every change audited.',
    features: [
      ['Edit order items', 'Add, remove or swap items on an unfulfilled order and settle the difference.', 'a'],
      ['Address changes', 'Let shoppers fix the shipping address before the order ships.', 'wa'],
      ['Order cancellation', 'Cancel orders with an automatic refund and restock.', 'ap'],
      ['Post-purchase upsell', 'Offer a one-click add-on on the thank-you page.', 'w'],
      ['Edit history', 'Keep an audit trail of every change made to an order.', 'ad'],
      ['Price adjustments', 'Apply goodwill discounts to an order after purchase.', 'a'],
      ['Self-service item swaps', 'Let shoppers swap size or color before the order ships.', 'w'],
    ],
  },
  {
    id: 'returns', domainId: 'orders', name: 'Returns & Exchanges', owner: 'fulfillment',
    summary: 'Returns, refunds and exchanges that shoppers can start on their own.',
    features: [
      ['Returns portal', 'Let shoppers start a return online and choose a reason and a method.', 'wm'],
      ['Return labels', 'Generate prepaid return labels or QR codes for drop-off.', 'k'],
      ['Exchanges', 'Swap items for another size or product without a refund cycle.', 'wa'],
      ['Return policies', 'Set return windows and rules by product, market and channel.', 'a'],
      ['Refund processing', 'Refund to the original payment, store credit or a gift card.', 'ak'],
      ['Return inspection', 'Record item condition on arrival and decide to restock or write off.', 'a'],
      ['Returns analytics', 'Show return rates and reasons by product and size.', 'ad'],
      ['Store credit', 'Issue refunds as store credit, with a bonus that keeps revenue.', 'ap'],
      ['Keep-the-item returns', 'Let shoppers keep low-value items instead of shipping them back.', 'k'],
      ['Return fraud checks', 'Flag serial returners and wear-and-return patterns.', 'k'],
    ],
  },
  // ── Inventory ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'stock', domainId: 'inventory', name: 'Stock & Locations', owner: 'fulfillment',
    summary: 'Stock counts across warehouses, shops and fulfillment partners.',
    features: [
      ['Multi-location stock', 'Track stock per warehouse, shop and logistics partner location.', 'ap'],
      ['Stock adjustments', 'Record received, damaged and counted stock with reasons.', 'a'],
      ['Stock transfers', 'Move stock between locations with in-transit tracking.', 'a'],
      ['Low-stock alerts', 'Notify buyers when stock drops below a set level.', 'k'],
      ['Stock sync service', 'Push stock changes to every sales channel within seconds.', 'k'],
      ['Cycle counts', 'Plan and record partial counts without closing the warehouse.', 'am'],
      ['Safety stock', 'Hold back units so channels do not oversell during sync delays.', 'p'],
      ['Barcode scanning', 'Scan barcodes with a phone to count and receive stock.', 'm'],
      ['Stock history', 'Keep a dated history of every change to stock levels.', 'ad'],
      ['Inventory API', 'Read and adjust stock levels from warehouse and ERP systems.', 'p'],
    ],
  },
  {
    id: 'purchasing', domainId: 'inventory', name: 'Purchasing', owner: 'fulfillment', since: '1.8',
    summary: 'Buying stock from suppliers and receiving it into locations.',
    features: [
      ['Purchase orders', 'Create purchase orders and send them to suppliers as PDF or email.', 'a'],
      ['Supplier directory', 'Keep supplier contacts, lead times and terms in one place.', 'a'],
      ['Receiving', 'Receive purchase orders in full or in part and update stock.', 'am'],
      ['Landed cost', 'Add freight and duties to unit costs for accurate margins.', 'ak'],
      ['Reorder suggestions', 'Suggest what to reorder based on sales velocity and lead time.', 'ak'],
      ['Supplier portal', 'Let suppliers confirm orders and share ship dates.', 'a'],
      ['Purchase approvals', 'Require approval for purchase orders above a set amount.', 'a'],
    ],
  },
  {
    id: 'forecasting', domainId: 'inventory', name: 'Forecasting', owner: 'fulfillment', since: '1.11',
    summary: 'Predicting demand so stock is in the right place at the right time.',
    features: [
      ['Demand forecast', 'Forecast unit demand per product and location for the next 12 weeks.', 'kd'],
      ['Seasonality detection', 'Spot seasonal patterns and holidays in sales history.', 'kd'],
      ['Stock-out risk', 'Flag products likely to sell out before the next delivery arrives.', 'ak'],
      ['Forecast accuracy report', 'Compare forecasts with actual sales to tune the model.', 'ad'],
      ['Promotion uplift', 'Adjust forecasts for planned sales and campaigns.', 'kd'],
      ['New product forecasts', 'Estimate demand for launches from similar products.', 'kd'],
    ],
  },
  // ── Shipping & Delivery ─────────────────────────────────────────────────────────────────────
  {
    id: 'labels', domainId: 'shipping', name: 'Rates & Labels', owner: 'fulfillment',
    summary: 'Shipping rates at checkout and labels in the warehouse.',
    features: [
      ['Live carrier rates', 'Show real-time rates from connected carriers at checkout.', 'p'],
      ['Shipping profiles', 'Set rates by zone, weight and product group.', 'a'],
      ['Label printing', 'Buy and print labels in bulk, with packing slips.', 'ak'],
      ['Customs forms', 'Generate commercial invoices and customs declarations.', 'k'],
      ['Carrier accounts', "Connect merchants' own carrier accounts.", 'a'],
      ['Rate shopping', 'Pick the cheapest carrier that meets the promised delivery date.', 'k'],
      ['Packaging presets', 'Save box sizes and weights to rate shipments accurately.', 'a'],
      ['Address validation', 'Validate and correct addresses before labels are bought.', 'p'],
      ['Pickup scheduling', 'Book carrier pickups from the admin.', 'a'],
      ['Shipping insurance', 'Offer insurance on high-value parcels at checkout.', 'wp'],
    ],
  },
  {
    id: 'tracking', domainId: 'shipping', name: 'Tracking', owner: 'fulfillment',
    summary: 'Keeping shoppers and merchants informed after the parcel leaves.',
    features: [
      ['Tracking page', 'Branded tracking page with carrier events and an estimated delivery date.', 'w'],
      ['Carrier event sync', 'Pull tracking events from carriers and normalize their statuses.', 'k'],
      ['Delivery notifications', 'Email and SMS updates when a parcel ships, is out for delivery and arrives.', 'k'],
      ['Delivery exceptions', 'Alert merchants about lost, delayed or returned parcels.', 'ak'],
      ['Proof of delivery', 'Store delivery photos and signatures with the order.', 'ap'],
      ['Tracking widget', 'Embed order tracking in the account page and the app.', 'wm'],
      ['Delivery promise accuracy', 'Compare promised and actual delivery dates per carrier.', 'ad'],
      ['Tracking API', 'Expose normalized tracking events to integrations.', 'p'],
    ],
  },
  {
    id: 'local-delivery', domainId: 'shipping', name: 'Local Delivery', owner: 'fulfillment', since: '1.10',
    summary: 'Same-day delivery and pickup for shops with local stock.',
    features: [
      ['Local delivery zones', 'Offer delivery by postcode or radius, with its own fee.', 'ap'],
      ['Delivery slots', 'Let shoppers book a delivery or pickup time slot.', 'w'],
      ['Route planning', "Plan efficient routes for a merchant's own drivers.", 'ak'],
      ['Driver app', 'A simple app for drivers with stops, navigation and proof of delivery.', 'm'],
      ['Store pickup', 'Buy online and collect in store, with ready-for-pickup alerts.', 'wa'],
      ['Courier dispatch', 'Book on-demand couriers for same-day orders.', 'k'],
    ],
  },
  // ── Customer Care ───────────────────────────────────────────────────────────────────────────
  {
    id: 'help', domainId: 'care', name: 'Help Center', owner: 'fulfillment',
    summary: 'Self-service answers before shoppers need to contact support.',
    features: [
      ['Help articles', 'Publish help articles with categories, search and feedback.', 'wa'],
      ['Help search', 'Search help articles, with suggestions drawn from support tickets.', 'w'],
      ['AI answer assistant', 'Answer shopper questions from help articles and order data.', 'wk'],
      ['Contact form routing', 'Route contact forms to the right team with order context.', 'wk'],
      ['Help center localization', 'Translate help articles for each market.', 'a'],
      ['Article analytics', 'See which articles prevent tickets and which need work.', 'ad'],
      ['Order lookup widget', 'Let shoppers check order status from the help center.', 'w'],
    ],
  },
  {
    id: 'support', domainId: 'care', name: 'Support Inbox', owner: 'fulfillment', since: '1.8',
    summary: 'One inbox for every customer conversation.',
    features: [
      ['Unified inbox', 'Email, chat and social messages in one shared inbox.', 'a'],
      ['Live chat', 'Chat with shoppers on the storefront, with typing indicators.', 'wa'],
      ['Customer context panel', 'Show orders, returns and loyalty status next to each conversation.', 'a'],
      ['Macros and snippets', 'Reply faster with saved answers that fill in order details.', 'a'],
      ['SLA timers', 'Track first response and resolution times against targets.', 'ak'],
      ['Ticket assignment', 'Assign conversations by skill, language and workload.', 'k'],
      ['Satisfaction surveys', 'Ask for a rating after each resolved conversation.', 'k'],
      ['Agent copilot', 'Draft replies and summarize long threads with AI.', 'ak'],
      ['Support analytics', 'Report volume, response times and satisfaction by team.', 'ad'],
      ['Help desk connectors', 'Connect the inbox to external help desks and CRMs.', 'p'],
    ],
  },
  {
    id: 'notifications', domainId: 'care', name: 'Notifications', owner: 'fulfillment',
    summary: 'Transactional email, SMS and push messages, with preferences.',
    features: [
      ['Order emails', 'Order confirmation, shipping and delivery emails.', 'k'],
      ['SMS notifications', 'Send order updates by SMS, with opt-in and opt-out.', 'k'],
      ['Notification templates', 'Edit message templates with variables and previews.', 'a'],
      ['Notification preferences', 'Let shoppers choose the channels and topics they hear about.', 'wm'],
      ['Delivery and bounce tracking', 'Track sends, opens, bounces and complaints.', 'kd'],
      ['Message queue', 'Queue and retry messages so traffic spikes do not drop sends.', 'k'],
      ['Quiet hours', 'Hold non-urgent messages outside daytime hours in each time zone.', 'k'],
      ['Notification localization', "Send each message in the shopper's language.", 'k'],
      ['Staff notifications', 'Alert staff about new orders, low stock and failed payouts.', 'ak'],
      ['Email sending domains', "Send from the merchant's own domain, with SPF and DKIM set up.", 'a'],
    ],
  },
  // ── Admin & Operations ──────────────────────────────────────────────────────────────────────
  {
    id: 'console', domainId: 'admin', name: 'Admin Console', owner: 'merchant',
    summary: 'The merchant admin home and its everyday tools.',
    features: [
      ['Admin home', 'A daily overview of sales, orders to fulfill and open tasks.', 'a'],
      ['Global admin search', 'Search products, orders, customers and settings from one box.', 'a'],
      ['Store settings', 'Configure store details, currency, languages and legal information.', 'a'],
      ['Activity log', 'See who changed what in the admin, and when.', 'ad'],
      ['Admin mobile app', 'Manage orders and products from a phone.', 'm'],
      ['Keyboard shortcuts', 'Navigate the admin and act on records without a mouse.', 'a'],
      ['Onboarding checklist', 'Guide new merchants through setup to their first sale.', 'a'],
      ['Customer records', 'View and edit customer profiles, notes and order history.', 'a'],
      ['Admin accessibility', 'Make every admin screen work with keyboards and screen readers.', 'a'],
      ['Admin notification center', 'Collect system notices and task reminders in one place.', 'a'],
    ],
  },
  {
    id: 'bulk', domainId: 'admin', name: 'Bulk Tools', owner: 'merchant',
    summary: 'Making the same change to many records at once.',
    features: [
      ['Bulk editor', 'Edit many products at once in a spreadsheet-style grid.', 'a'],
      ['Bulk actions', 'Tag, archive or publish many records in one step.', 'ak'],
      ['Import jobs', 'Import customers, orders and stock from CSV with validation.', 'ak'],
      ['Export jobs', 'Export any list view to CSV or Excel in the background.', 'ak'],
      ['Scheduled jobs', 'Run imports and exports on a schedule from SFTP.', 'k'],
      ['Job history', 'Track progress, errors and downloads for bulk jobs.', 'a'],
      ['Undo bulk changes', 'Roll back a bulk edit within 24 hours.', 'ak'],
    ],
  },
  {
    id: 'staff', domainId: 'admin', name: 'Staff & Roles', owner: 'merchant',
    summary: 'Staff accounts, roles and permissions.',
    features: [
      ['Staff accounts', 'Invite staff and manage their access.', 'a'],
      ['Custom roles', 'Create roles with fine-grained permissions.', 'ap'],
      ['Location permissions', 'Limit staff to specific shops and warehouses.', 'a'],
      ['Staff two-step sign-in', 'Require two-step verification for all staff.', 'ap'],
      ['Single sign-on', 'Let staff sign in with the company identity provider.', 'p'],
      ['Approval workflows', 'Require a second person to approve sensitive changes.', 'a'],
      ['Staff audit export', 'Export staff access and permission changes for audits.', 'ad'],
      ['Collaborator access', 'Give agencies limited, time-boxed access to a store.', 'a'],
    ],
  },
  // ── Analytics ───────────────────────────────────────────────────────────────────────────────
  {
    id: 'events', domainId: 'analytics', name: 'Event Pipeline', owner: 'merchant',
    summary: 'Collecting storefront, app and server events reliably and with consent.',
    features: [
      ['Event collector', 'Collect page views, clicks and cart events from the web and the app.', 'pk'],
      ['Server-side events', 'Record orders, refunds and fulfillments as trusted server events.', 'k'],
      ['Consent-aware tracking', 'Drop or anonymize events when a shopper has not given consent.', 'pk'],
      ['Event schema registry', 'Define and version event schemas, and reject malformed events.', 'd'],
      ['Event replay', 'Replay raw events to rebuild reports after a fix.', 'kd'],
      ['Ad platform connectors', 'Send conversion events to ad platforms server to server.', 'k'],
      ['Bot filtering', 'Exclude bots and crawlers from analytics.', 'k'],
      ['Real-time event stream', "Stream events to merchants' own data warehouses.", 'pd'],
    ],
  },
  {
    id: 'reports', domainId: 'analytics', name: 'Reports', owner: 'merchant',
    summary: 'Standard reports merchants use to run the business.',
    features: [
      ['Sales report', 'Sales by day, channel, product and region, with comparisons.', 'ad'],
      ['Finance summary', 'Gross sales, discounts, returns, taxes and net sales for accounting.', 'ad'],
      ['Product performance', 'Views, add-to-cart rate, conversion and returns for each product.', 'ad'],
      ['Customer cohorts', 'Repeat purchase rate and lifetime value by first-order month.', 'ad'],
      ['Inventory report', 'Stock value, sell-through and days of cover.', 'ad'],
      ['Custom report builder', 'Build reports from any metric and dimension, and save them.', 'ad'],
      ['Scheduled reports', 'Email reports to the team daily, weekly or monthly.', 'k'],
      ['Report exports', 'Export any report to CSV or a spreadsheet.', 'ak'],
      ['Marketing attribution', 'Attribute sales to channels and campaigns.', 'ad'],
      ['Live view', 'Watch visitors, carts and orders as they happen.', 'a'],
    ],
  },
  {
    id: 'insights', domainId: 'analytics', name: 'Insights', owner: 'merchant', since: '1.10',
    summary: 'Automatic explanations of what changed and why.',
    features: [
      ['Anomaly alerts', 'Notice unusual drops or spikes in sales, traffic or conversion.', 'kd'],
      ['Weekly digest', "A plain-language summary of the week's performance.", 'k'],
      ['Benchmarks', 'Compare store metrics with similar stores.', 'ad'],
      ['Conversion funnel', 'Show where shoppers drop off between landing and purchase.', 'ad'],
      ['Ask your data', 'Answer questions about store data in plain language.', 'ak'],
      ['Revenue outlook', 'Projected revenue for the month, with confidence bands.', 'ad'],
      ['Opportunity cards', 'Suggest actions such as restocking a fast seller.', 'a'],
    ],
  },
  // ── Integrations ────────────────────────────────────────────────────────────────────────────
  {
    id: 'public-api', domainId: 'integrations', name: 'Public API', owner: 'merchant',
    summary: 'The REST and GraphQL APIs that apps and partners build on.',
    features: [
      ['REST Admin API', 'Versioned REST endpoints for products, orders, customers and more.', 'p'],
      ['GraphQL Storefront API', 'Query catalog, cart and checkout data for custom storefronts.', 'p'],
      ['API keys and scopes', 'Issue API keys limited to the scopes an app needs.', 'ap'],
      ['OAuth for apps', 'Let third-party apps request access through OAuth consent.', 'wp'],
      ['Rate limiting', 'Fair-use limits per app, with clear headers and retry hints.', 'p'],
      ['API versioning', 'Quarterly API versions with deprecation notices.', 'p'],
      ['API reference docs', 'Generated reference docs with examples for every endpoint.', 'w'],
      ['Bulk operations API', 'Run large queries and mutations as background jobs.', 'pk'],
      ['API usage dashboard', 'Show calls, errors and throttling for each app.', 'ad'],
      ['SDKs', 'Official client libraries for JavaScript, Python and PHP.', 'p'],
    ],
  },
  {
    id: 'webhooks', domainId: 'integrations', name: 'Webhooks', owner: 'merchant', since: '1.6',
    summary: 'Pushing events to apps the moment they happen.',
    features: [
      ['Webhook subscriptions', 'Subscribe apps to order, product and customer events.', 'ap'],
      ['Signed deliveries', 'Sign every webhook so receivers can verify it.', 'k'],
      ['Retry and backoff', 'Retry failed deliveries with backoff for up to 48 hours.', 'k'],
      ['Delivery log', "See each delivery's payload, response and timing.", 'a'],
      ['Event filters', 'Subscribe only to events that match field filters.', 'p'],
      ['Event bridge targets', 'Deliver events to cloud queues instead of HTTP endpoints.', 'k'],
      ['Webhook health alerts', 'Warn developers when an endpoint keeps failing.', 'k'],
    ],
  },
  {
    id: 'channels', domainId: 'integrations', name: 'Channels & Marketplaces', owner: 'merchant', since: '1.8',
    summary: 'Selling on marketplaces, social shops and in person from one catalog.',
    features: [
      ['Marketplace listings', 'Publish products to major marketplaces with mapped categories.', 'ak'],
      ['Channel order import', 'Pull marketplace orders into Larkspur for fulfillment.', 'k'],
      ['Social shops', 'Sync the catalog to social media shops.', 'ak'],
      ['Product feeds', 'Generate shopping feeds for search engines and comparison sites.', 'k'],
      ['Channel pricing', 'Set channel-specific prices and markups.', 'a'],
      ['Channel stock buffers', 'Keep a stock buffer per channel to prevent overselling.', 'ak'],
      ['Point of sale', 'Sell in physical shops with shared stock and customers.', 'am'],
      ['Wholesale portal', 'A B2B ordering portal with price lists and payment terms.', 'w'],
      ['Channel performance', 'Compare sales, fees and returns across channels.', 'ad'],
    ],
  },
  {
    id: 'app-store', domainId: 'integrations', name: 'App Store', owner: 'merchant', since: '1.11',
    summary: 'Third-party apps that extend Larkspur, and the partners who build them.',
    features: [
      ['App directory', 'Browse and search apps by category, rating and price.', 'wa'],
      ['App installs', 'Install apps with a permission review, and uninstall them cleanly.', 'a'],
      ['App billing', 'Charge merchants for apps through their Larkspur invoice.', 'k'],
      ['App ratings', 'Ratings and reviews from merchants who use each app.', 'w'],
      ['Partner dashboard', 'Let developers manage listings, installs and payouts.', 'a'],
      ['App review process', 'Check new apps for security, performance and policy before listing.', 'a'],
      ['App extensions', 'Let apps add blocks to the admin, checkout and storefront.', 'wap'],
      ['App performance scores', 'Score apps by their impact on store speed.', 'kd'],
    ],
  },
  // ── Identity & Access ───────────────────────────────────────────────────────────────────────
  {
    id: 'auth', domainId: 'identity', name: 'Authentication', owner: 'platform',
    summary: 'Signing in shoppers and staff safely.',
    features: [
      ['Email and password sign-in', 'Classic sign-in with checks against breached passwords.', 'wap'],
      ['Passkeys', 'Passwordless sign-in with device passkeys.', 'wmp'],
      ['Social sign-in', 'Sign in with Apple, Google and Facebook accounts.', 'wmp'],
      ['Magic links', 'One-time sign-in links sent by email.', 'wp'],
      ['Two-step verification', 'Authenticator app and SMS codes for extra protection.', 'wap'],
      ['Password reset', 'Secure password reset with expiring tokens.', 'wp'],
      ['Brute-force protection', 'Throttle and challenge suspicious sign-in attempts.', 'k'],
      ['Identity provider service', 'The OpenID Connect provider behind every sign-in.', 'p'],
      ['Sign-in analytics', 'Track sign-in success, failures and the mix of methods.', 'ad'],
      ['Account recovery', 'Recover accounts that lost access to their email or devices.', 'wa'],
      ['Session tokens', 'Issue and rotate short-lived access and refresh tokens.', 'p'],
      ['Enterprise SAML', 'SAML single sign-on for large merchant teams.', 'ap'],
    ],
  },
  {
    id: 'accounts', domainId: 'identity', name: 'Accounts & Privacy', owner: 'platform',
    summary: 'Customer accounts and the privacy rights that come with them.',
    features: [
      ['Customer accounts', 'Account page with profile, addresses and order history.', 'wm'],
      ['Address book', 'Save several shipping and billing addresses.', 'wmp'],
      ['Marketing consent', 'Record email and SMS consent with its source and timestamp.', 'wap'],
      ['Cookie consent banner', 'Ask for cookie consent and enforce it across scripts.', 'w'],
      ['Data export requests', 'Let shoppers download all the data held about them.', 'wk'],
      ['Account deletion', "Delete or anonymize a shopper's data on request.", 'wk'],
      ['Privacy request queue', 'Track access and erasure requests against legal deadlines.', 'a'],
      ['Data retention rules', 'Delete old personal data automatically according to policy.', 'kd'],
      ['Customer segments', 'Group customers by behavior for marketing and pricing.', 'ad'],
      ['Customer merge', 'Merge duplicate customer records safely.', 'a'],
    ],
  },
  {
    id: 'sessions', domainId: 'identity', name: 'Sessions & Devices', owner: 'platform',
    summary: 'Keeping shoppers and staff signed in safely across devices.',
    features: [
      ['Session management', 'Keep shoppers signed in across visits with secure cookies.', 'p'],
      ['Device list', 'Show signed-in devices and let people sign them out.', 'wa'],
      ['Remember me', 'Optional long-lived sessions on trusted devices.', 'w'],
      ['Session anomaly alerts', 'Email people about sign-ins from new devices or places.', 'k'],
      ['Staff session policies', 'Set idle timeouts and IP allow lists for staff.', 'a'],
      ['Cross-domain sessions', 'Share sign-in between the store, checkout and help center domains.', 'p'],
      ['Session revocation', 'Revoke sessions instantly after a password change.', 'p'],
    ],
  },
  // ── Platform & Reliability ──────────────────────────────────────────────────────────────────
  {
    id: 'infrastructure', domainId: 'platform', name: 'Infrastructure', owner: 'platform',
    summary: 'The cloud foundations every service runs on.',
    features: [
      ['Container platform', 'Run every service on managed containers with autoscaling.', 'k'],
      ['Multi-region failover', 'Fail over to a second region with tested runbooks.', 'k'],
      ['Edge caching', 'Cache storefront pages and assets at the edge.', 'w'],
      ['Database cluster', 'Managed Postgres with replicas, backups and point-in-time recovery.', 'd'],
      ['Cache layer', 'Shared Redis for sessions, carts and rate limits.', 'd'],
      ['Job queue', 'Background job queue with priorities and dead-letter handling.', 'k'],
      ['Secrets management', 'Store and rotate secrets without exposing them to code.', 'k'],
      ['Infrastructure as code', 'Every environment defined in Terraform and reviewed.', 'k'],
      ['Preview environments', 'Spin up a full environment per branch for demos and tests.', 'k'],
      ['Blue-green deploys', 'Switch traffic to a new release with instant rollback.', 'k'],
      ['Backup and restore', 'Daily backups with monthly restore drills.', 'd'],
      ['Cost allocation tags', 'Tag cloud resources by team and feature for cost reports.', 'd'],
    ],
  },
  {
    id: 'observability', domainId: 'platform', name: 'Observability', owner: 'platform',
    summary: 'Seeing how Larkspur behaves in production.',
    features: [
      ['Central logging', 'Collect structured logs from every service, with search.', 'kd'],
      ['Metrics and dashboards', 'Service metrics and dashboards for every team.', 'k'],
      ['Distributed tracing', 'Trace requests across services to find slow spots.', 'k'],
      ['SLO tracking', 'Define service level objectives and track error budgets.', 'k'],
      ['Alerting and on-call', 'Route alerts to the right on-call engineer.', 'k'],
      ['Status page', 'Public status page with incident updates.', 'w'],
      ['Real user monitoring', "Measure page speed in shoppers' browsers.", 'wk'],
      ['Synthetic checks', 'Run scripted checkouts every minute from several regions.', 'k'],
      ['Incident timeline', 'Record incident actions and draft the postmortem.', 'a'],
      ['Error tracking', 'Group exceptions by cause and link them to releases.', 'k'],
    ],
  },
  {
    id: 'data-platform', domainId: 'platform', name: 'Data Platform', owner: 'platform',
    summary: 'Warehousing, pipelines and governance for Larkspur data.',
    features: [
      ['Data warehouse', 'Central warehouse fed from production databases and events.', 'd'],
      ['Change data capture', 'Stream database changes to the warehouse in near real time.', 'kd'],
      ['Pipeline orchestration', 'Schedule and monitor data pipelines, with retries.', 'k'],
      ['Data quality checks', 'Test freshness, volume and schema of every key table.', 'kd'],
      ['Data catalog', 'Document tables, owners and lineage.', 'd'],
      ['PII tagging', 'Tag personal data columns and mask them for analysts.', 'd'],
      ['Feature store', 'Share model features for fraud, search and recommendations.', 'd'],
      ['Merchant data exports', "Deliver a merchant's data to their own warehouse.", 'kd'],
      ['Query cost limits', 'Cap runaway warehouse queries before they cost too much.', 'k'],
    ],
  },
];

// Six human squads own modules and review work; five agent crews build. Squad ids are short because they
// appear in every automated ledger entry (as the owner of the pipeline that ran).
export const teams = [
  { id: 'shopper', name: 'Shopper Squad', kind: 'human' },
  { id: 'checkout', name: 'Checkout Squad', kind: 'human' },
  { id: 'payments', name: 'Payments Squad', kind: 'human' },
  { id: 'fulfillment', name: 'Fulfillment Squad', kind: 'human' },
  { id: 'merchant', name: 'Merchant Squad', kind: 'human' },
  { id: 'platform', name: 'Platform Squad', kind: 'human' },
  { id: 'loom', name: 'Loom crew', kind: 'agent' },
  { id: 'forge', name: 'Forge crew', kind: 'agent' },
  { id: 'tempo', name: 'Tempo crew', kind: 'agent' },
  { id: 'relay', name: 'Relay crew', kind: 'agent' },
  { id: 'sentry', name: 'Sentry crew', kind: 'agent' },
];

// Automated systems that write ledger entries (actorKind 'system'): CI, deploys, monitors, scanners and exports.
export const systems = [
  { id: 'ci', name: 'CI pipeline', kind: 'pipeline' },
  { id: 'deploy', name: 'Deploy pipeline', kind: 'pipeline' },
  { id: 'slo', name: 'SLO monitor', kind: 'monitor' },
  { id: 'sast', name: 'Security scanner', kind: 'scanner' },
  { id: 'perfscan', name: 'Performance scanner', kind: 'scanner' },
  { id: 'compscan', name: 'Compliance scanner', kind: 'scanner' },
  { id: 'a11yscan', name: 'Accessibility scanner', kind: 'scanner' },
  { id: 'costs', name: 'Cloud cost export', kind: 'export' },
  { id: 'tickets', name: 'Ticket sync', kind: 'sync' },
];

// The agent crew that builds most work in each area (security work always goes to Sentry).
export const areaCrew = { shopper: 'loom', commerce: 'forge', fulfillment: 'tempo', merchant: 'relay', foundation: 'sentry' };

export const people = [
  { id: 'amara-osei', name: 'Amara Osei', role: 'executive', team: 'platform' },
  { id: 'jonas-weber', name: 'Jonas Weber', role: 'executive', team: 'fulfillment' },
  { id: 'priya-raman', name: 'Priya Raman', role: 'product', team: 'checkout' },
  { id: 'diego-navarro', name: 'Diego Navarro', role: 'product', team: 'shopper' },
  { id: 'hannah-cho', name: 'Hannah Cho', role: 'product', team: 'merchant' },
  { id: 'kwame-boateng', name: 'Kwame Boateng', role: 'product', team: 'fulfillment' },
  { id: 'lucia-fernandez', name: 'Lucía Fernández', role: 'engineering', team: 'payments' },
  { id: 'noah-kowalski', name: 'Noah Kowalski', role: 'engineering', team: 'payments' },
  { id: 'samuel-mensah', name: 'Samuel Mensah', role: 'engineering', team: 'checkout' },
  { id: 'aiko-tanaka', name: 'Aiko Tanaka', role: 'engineering', team: 'shopper' },
  { id: 'mei-lin-chou', name: 'Mei-Lin Chou', role: 'engineering', team: 'shopper' },
  { id: 'rafael-costa', name: 'Rafael Costa', role: 'engineering', team: 'fulfillment' },
  { id: 'elif-demir', name: 'Elif Demir', role: 'engineering', team: 'merchant' },
  { id: 'tomasz-nowak', name: 'Tomasz Nowak', role: 'engineering', team: 'platform' },
  { id: 'grace-adeyemi', name: 'Grace Adeyemi', role: 'operations', team: 'platform' },
  { id: 'oskar-lindqvist', name: 'Oskar Lindqvist', role: 'operations', team: 'platform' },
  { id: 'fatima-al-sayed', name: 'Fatima Al-Sayed', role: 'security', team: 'platform' },
  { id: 'marcus-bell', name: 'Marcus Bell', role: 'security', team: 'payments' },
  { id: 'sofia-marchetti', name: 'Sofia Marchetti', role: 'design', team: 'shopper' },
  { id: 'ananya-iyer', name: 'Ananya Iyer', role: 'design', team: 'checkout' },
  { id: 'henrik-larsen', name: 'Henrik Larsen', role: 'compliance', team: 'payments' },
  { id: 'zainab-hassan', name: 'Zainab Hassan', role: 'compliance', team: 'merchant' },
];

// Releases: 12 shipped about every six weeks, one next and two future. `highlights` are feature names
// the generator ships (or targets) in that release so the summary stays true; they are not output.
export const releases = [
  { id: '1.0', date: '2025-06-10', name: 'Aster', summary: 'Launch release: product records, the cart drawer, one-page checkout with card payments, the order timeline and the admin home.', highlights: ['Product records', 'Cart drawer', 'One-page checkout', 'Card payments', 'Order timeline', 'Admin home'] },
  { id: '1.1', date: '2025-07-22', name: 'Bluebell', summary: 'Product search, discount codes, label printing and customer accounts.', highlights: ['Product search', 'Discount codes', 'Label printing', 'Customer accounts'] },
  { id: '1.2', date: '2025-09-02', name: 'Camellia', summary: 'A self-service returns portal, multi-location stock, the tax engine and the REST Admin API.', highlights: ['Returns portal', 'Multi-location stock', 'Tax engine', 'REST Admin API'] },
  { id: '1.3', date: '2025-10-14', name: 'Dahlia', summary: 'Express pay buttons, fraud scoring and scheduled merchant payouts.', highlights: ['Express pay buttons', 'Fraud scoring', 'Merchant payouts'] },
  { id: '1.4', date: '2025-11-25', name: 'Edelweiss', summary: 'Holiday readiness: a flash sale scheduler, digital gift cards and multi-region failover.', highlights: ['Flash sale scheduler', 'Digital gift cards', 'Multi-region failover'] },
  { id: '1.5', date: '2026-01-13', name: 'Foxglove', summary: 'Subscribe and save with renewal billing, plus the first sales report.', highlights: ['Subscribe and save', 'Renewal billing', 'Sales report'] },
  { id: '1.6', date: '2026-02-24', name: 'Gardenia', summary: 'Product reviews, webhook subscriptions and the bulk editor.', highlights: ['Product reviews', 'Webhook subscriptions', 'Bulk editor'] },
  { id: '1.7', date: '2026-04-07', name: 'Heather', summary: 'Related products, the loyalty points program and SMS notifications.', highlights: ['Related products', 'Points program', 'SMS notifications'] },
  { id: '1.8', date: '2026-05-19', name: 'Iris', summary: 'Marketplace listings, purchase orders and a unified support inbox.', highlights: ['Marketplace listings', 'Purchase orders', 'Unified inbox'] },
  { id: '1.9', date: '2026-06-30', name: 'Jasmine', summary: 'Passkeys, a privacy request queue and an accessibility pass across checkout.', highlights: ['Passkeys', 'Privacy request queue', 'Checkout accessibility'] },
  { id: '1.10', date: '2026-08-11', name: 'Kalmia', summary: 'Native app navigation in beta, store pickup and anomaly alerts.', highlights: ['Native app navigation', 'Store pickup', 'Anomaly alerts'] },
  { id: '1.11', date: '2026-09-22', name: 'Lupin', summary: 'The app directory, demand forecasts and native checkout in the app.', highlights: ['App directory', 'Demand forecast', 'Native checkout'] },
  { id: '1.12', date: '2026-11-03', name: 'Magnolia', summary: 'The payments core refactor lands with multi-acquirer routing and instant payouts, plus product Q&A.', highlights: ['Multi-acquirer routing', 'Instant payouts', 'Product Q&A'] },
  { id: '2.0', date: '2027-01-26', name: 'Nasturtium', summary: 'The app grows up: shoppable stories, creator profiles and a wholesale portal for B2B buyers.', highlights: ['Shoppable stories', 'Creator profiles', 'Wholesale portal'] },
  { id: '2.1', date: '2027-04-13', name: 'Orchid', summary: 'AI assistance: visual search, ask-your-data insights and an answer assistant in the help center.', highlights: ['Visual search', 'Ask your data', 'AI answer assistant'] },
];

export const initiatives = [
  {
    id: 'compliance-scan', name: 'Legal compliance scan coverage', kind: 'permanent', type: 'compliance-scan',
    summary: 'Continuous scans for GDPR, PCI DSS, SOC 2 and EAA controls on every feature that handles regulated data or shopper-facing UI.',
    owner: 'henrik-larsen', startedAt: '2025-09-01', endsAt: null,
  },
  {
    id: 'a11y-monitoring', name: 'Accessibility monitoring', kind: 'permanent', type: 'a11y-monitoring',
    summary: 'Automated WCAG checks on every screen, with findings triaged by design before they reach the backlog.',
    owner: 'sofia-marchetti', startedAt: '2026-02-02', endsAt: null,
  },
  {
    id: 'payments-refactor', name: 'Payments core refactor', kind: 'temporary', type: 'refactor',
    summary: 'Moves Payments and Checkout onto one payments core with idempotent intents and network tokens.',
    owner: 'lucia-fernandez', startedAt: '2026-08-17', endsAt: '2026-12-11',
  },
  {
    id: 'perf-scan-2026-10', name: 'Performance scan October 2026', kind: 'temporary', type: 'scan',
    summary: 'A one-month scan of Search, Storefront and Checkout against latency SLOs; findings wait for developer triage.',
    owner: 'grace-adeyemi', startedAt: '2026-10-01', endsAt: '2026-10-30',
  },
  {
    id: 'node-22', name: 'Runtime upgrade to Node 22', kind: 'temporary', type: 'upgrade',
    summary: 'Upgrades every worker service from Node 18 to Node 22 before Node 18 support ends.',
    owner: 'tomasz-nowak', startedAt: '2026-09-07', endsAt: '2026-11-20',
  },
  {
    id: 'cost-sprint', name: 'Cloud cost reduction sprint', kind: 'temporary', type: 'cost',
    summary: 'A four-week push to bring features that run over their cloud budget back under it.',
    owner: 'oskar-lindqvist', startedAt: '2026-09-28', endsAt: '2026-10-23',
  },
];

// ── Pools ─────────────────────────────────────────────────────────────────────────────────────
// Placeholders: {name} feature name, {dep} a dependency's name, {p95} {slo} ms, {n} a count, {pct} a percent.
// Finding titles leave out the feature name: they always appear on, or next to, their feature.
// Each perf, security and cost finding names the surfaces it can occur on.

// Blocked reasons: domain-specific ones first, general ones for everything else.
export const blockedReasons = {
  any: [
    'Design for the empty and error states is not approved yet.',
    'The load test environment is unavailable until the cluster upgrade lands.',
    'Needs a product decision on the scope of the first release.',
    'Waiting for the platform team to provision a new queue.',
  ],
  byDomain: {
    storefront: ['Waiting for the CDN vendor to support the new cache rules.', 'Needs a decision on how translated URLs are structured.'],
    discovery: ['The search vendor contract renewal is still in negotiation.', 'Needs a decision on how personal data may be used for ranking.'],
    community: ['Legal has not signed off the moderation policy for user content.', 'Waiting for the trust and safety review of public profiles.'],
    mobile: ['App store review rejected the build; waiting for a ruling on the in-app purchase rule.', 'Waiting for the app signing keys to move to the new vault.'],
    checkout: ['Waiting for the payments core refactor to expose the new intents API.', 'Needs a decision on which options launch first in each market.'],
    payments: ['Waiting for the acquirer to certify the new message format.', 'Security review found a design flaw in token storage; the approach is being reworked.'],
    pricing: ['Waiting for legal guidance on EU pricing and gift card rules.', 'Needs finance sign-off on how promotions are accounted for.'],
    billing: ['Waiting for the tax provider to enable the new rates API in production.', 'Needs a schema migration that is frozen until the payments refactor finishes.'],
    orders: ['Needs a product decision on refunds for partially returned bundles.', 'Waiting for the warehouse partner to support split shipments in their API.'],
    inventory: ['Waiting for the ERP vendor to open their stock API to Larkspur.', 'Needs agreement with finance on how stock is valued.'],
    shipping: ["Waiting for the carrier's sandbox credentials.", 'The carrier changed its label format; the integration needs recertification.'],
    care: ['The support tooling vendor has not signed the data processing agreement.', 'Needs support leads to agree on the new workflow.'],
    admin: ['Needs a decision on the permission model for agencies.', 'Waiting for the design system update to the admin tables.'],
    analytics: ['Legal has not signed off the consent wording for the EU markets.', 'The warehouse migration freezes new event schemas until November.'],
    integrations: ['The marketplace API is rate limited below what the feature needs; contract talks are ongoing.', 'Waiting for partner feedback on the API version change.'],
    identity: ['Security review found a design flaw in token storage; the approach is being reworked.', 'Waiting for the identity provider upgrade in both regions.'],
    platform: ['Blocked by the Node 22 upgrade of the shared worker image.', 'Waiting for the cloud provider to raise the regional quota.'],
  },
};
export const dependencyBlockedReason = 'Waiting on {dep}, which is still in build.';

// Which other domains a domain's features may depend on (besides their own domain).
export const domainDependencies = {
  storefront: ['platform', 'identity'],
  discovery: ['storefront', 'analytics', 'platform'],
  community: ['storefront', 'orders', 'identity'],
  mobile: ['storefront', 'discovery', 'checkout', 'identity', 'care', 'community'],
  checkout: ['storefront', 'pricing', 'payments', 'shipping', 'identity'],
  payments: ['identity', 'platform'],
  pricing: ['storefront', 'identity'],
  billing: ['payments', 'identity', 'platform'],
  orders: ['checkout', 'payments', 'inventory', 'platform'],
  inventory: ['storefront', 'orders', 'platform'],
  shipping: ['orders', 'inventory', 'platform'],
  care: ['orders', 'shipping', 'identity', 'platform'],
  admin: ['identity', 'platform'],
  analytics: ['orders', 'identity', 'platform'],
  integrations: ['storefront', 'orders', 'inventory', 'identity', 'platform'],
  identity: ['platform'],
  platform: [],
};

export const featureNotes = [
  'Behind a feature flag for 40 pilot stores.',
  'Most used by stores on the Plus plan.',
  'Shares its data model with the wholesale tools.',
  'Jointly reviewed with the security team at each release.',
  'Merchants asked for this in the last two surveys.',
  'Runs in both regions; failover tested in September.',
  'Pilot with three apparel brands before a wider launch.',
  'Rebuilt by an agent crew in the last quarter.',
];

// Reviewer notes on a branch with changes requested, chosen by what the branch does (see generate.mjs:
// reviewNotePool): the work item kind first, then the feature's main surface, then the money domains.
export const reviewerNotes = {
  fix: [
    'The fix has no regression test. Add the failing case first, then the fix.',
    'The report does not show the bug reproducing before the fix. Add the before run.',
  ],
  perf: [
    'The report shows p95 only with a warm cache. Rerun the load test with cold starts.',
    'The gain comes from a bigger cache, not the query. Show the query plan before and after.',
  ],
  security: [
    'The scan in the report predates the patch. Rescan the branch and attach the new result.',
    'The patch blocks the exploit path in the demo but not the batch import. Cover both.',
  ],
  a11y: [
    'Keyboard focus is lost after the dialog closes. Fix it and record the screen reader pass.',
    'The fix covers the desktop layout only. Check the 390 px layout too.',
  ],
  refactor: [
    'Two contract tests were skipped, not fixed. Re-enable them before merging.',
    'The old code path is still on for new stores. Flag it off by default.',
  ],
  cost: [
    'The cost estimate leaves out the extra queue workers. Add them to the report.',
    'Savings assume last month\'s traffic. Show the estimate at peak load as well.',
  ],
  web: [
    'The demo skips the error path. Show what happens when the request fails.',
    'Copy on the confirmation step needs product review; it promises more than we can guarantee.',
    'Numbers in the demo do not match the seeded data. Rerun the demo on a fresh preview environment.',
  ],
  admin: [
    'The admin action is missing an audit log entry.',
    'Bulk changes need a confirmation step that says how many records change.',
  ],
  mobile: [
    'The demo only covers iOS. Record the Android build as well.',
    'Offline behaviour is not shown. Demo the flow with the network off.',
  ],
  api: [
    'The new endpoint returns personal data without checking the scope. Gate it behind the right permission.',
    'Please split the schema migration from the feature change so it can be rolled back alone.',
  ],
  worker: [
    'The fallback hides real errors from on-call. Log and alert instead of retrying silently.',
    'Retries need a cap and a dead-letter queue before this can run at peak.',
  ],
  data: [
    'The backfill has no dry run. Add one and attach its row counts.',
  ],
  money: [
    'The demo skips the declined-payment path. Show what the shopper sees when the card is declined.',
    'Feature flag defaults to on. It must start off for existing stores.',
  ],
};

export const findings = {
  // [title, surfaces it applies to: w web, a admin, m mobile, p api, k worker, d data, * any]
  perf: [
    ['p95 of {p95} ms is over the {slo} ms SLO', '*'],
    ['N+1 queries on page load', 'wa'],
    ['Unindexed sort in the main query', 'pad'],
    ['{n} KB of unused JavaScript', 'w'],
    ['Blocking third-party script', 'w'],
    ['Cache hit rate of only {pct}%', 'wp'],
    ['Layout shift above 0.1', 'w'],
    ['Uncompressed images', 'wm'],
    ['Job queue backs up at peak', 'k'],
  ],
  security: [
    ['Dependency with a known CVE', '*'],
    ['Missing rate limit on a public endpoint', 'p'],
    ['Stack traces leak in error responses', 'wp'],
    ['Session cookie without SameSite', 'wa'],
    ['Server-side request forgery risk', 'pk'],
    ['Over-broad IAM role', 'kd'],
    ['Unvalidated redirect parameter', 'w'],
    ['Admin action without a permission check', 'a'],
    ['Secrets read from plain environment files', 'k'],
  ],
  a11y: [
    'Form fields without labels',
    'Text contrast below 4.5:1',
    'Focus trapped in a dialog',
    'Images without alt text',
    'Keyboard cannot reach all controls',
    'Status changes not announced',
  ],
  compliance: {
    GDPR: ['Consent not recorded before tracking', 'Retention period not enforced', 'Personal data in logs'],
    'PCI DSS': ['Card data pattern in debug logs', 'Quarterly key rotation overdue', 'Segmentation test missing'],
    'SOC 2': ['Access review overdue', 'Deploy without change approval', 'Restore test not recorded'],
    EAA: ['Accessibility statement missing', 'No alternative to drag and drop', 'Video without captions'],
  },
  cost: [
    ['Idle worker capacity overnight', 'k'],
    ['Unbounded retries inflate queue costs', 'k'],
    ['Logs kept in hot storage', '*'],
    ['Oversized database instance', 'pad'],
    ['Cache misses drive extra compute', 'wp'],
    ['Uncompressed media in hot storage', 'wm'],
  ],
};

// Asks that land in a live feature's backlog, keyed by the feature's main surface.
export const asks = {
  web: ['add skeleton loading states', 'support right-to-left languages', 'remember the last choice', 'improve the empty state', 'show prices in the local currency', 'work at 400% zoom', 'add a compact mobile layout', 'explain errors in plain words'],
  admin: ['add CSV export', 'filter by date range', 'bulk edit from the list', 'show change history', 'add saved views', 'add keyboard shortcuts', 'show totals per location', 'add a permissions check per staff role'],
  mobile: ['support tablet layouts', 'add haptic feedback', 'work offline for longer', 'support dynamic type sizes', 'add a widget entry point'],
  api: ['add cursor pagination', 'expose it in GraphQL', 'add idempotency keys', 'return localized errors', 'add a webhook event', 'raise the batch size limit'],
  worker: ['retry with backoff', 'alert on the dead-letter queue', 'cut the run time in half', 'partition work by store', 'backfill two years of history', 'add a dry-run mode'],
  data: ['add column-level lineage', 'partition by month', 'add freshness alerts', 'document every column', 'mask personal data for analysts'],
};

// Bugs synced from the ticketing system: [title, surfaces it can occur on (w a m p k d, * any), domains it
// belongs to (space separated) or null for any domain]. The generator only picks a bug that fits the feature.
export const bugs = [
  ['wrong totals after a currency switch', 'wmap', 'checkout payments pricing billing orders'],
  ['rounding error on tax-inclusive prices', '*', 'checkout pricing billing orders'],
  ['refund issued twice when a webhook is retried', 'pk', 'payments orders billing'],
  ['stock goes negative under concurrent orders', 'pka', 'inventory orders checkout'],
  ['label prints with the wrong return address', 'ak', 'shipping orders'],
  ['tracking page shows a stale delivery status', 'wm', 'shipping orders care'],
  ['search results flicker while typing', 'wm', 'discovery'],
  ['session expires halfway through a long form', 'wam', 'identity checkout billing'],
  ['report totals differ from the CSV export', 'ad', 'analytics billing'],
  ['webhook retries never give up', 'pk', 'integrations payments'],
  ['times out on stores with 50,000 orders', 'apkd', null],
  ['duplicate events after a retry', 'pkd', null],
  ['wrong time zone in the date filter', 'a', null],
  ['button hidden behind the cookie banner on small screens', 'w', null],
  ['crashes when the list is empty', 'wam', null],
  ['double submit on slow networks', 'wm', null],
  ['stale data after an undo', 'a', null],
  ['emoji in names break the export', 'ad', null],
  ['sorting ignores accented characters', 'wa', null],
  ['fails silently when the upstream API returns 429', 'pk', null],
  ['push notification opens the wrong screen', 'm', null],
  ['images load twice on slow connections', 'wm', null],
];

export const ticketAsks = [
  'merchant request from the support inbox',
  'agency partner request',
  'raised in the quarterly merchant council',
  'top request on the feedback board',
];

export const evidence = {
  demo: [
    { title: 'Demo: {name} end to end', summary: 'Happy path and errors on a preview environment.' },
    { title: 'Walkthrough: {name}', summary: 'At 1440 and 390 px, with a screen reader pass.' },
    { title: 'Pilot store recording: {name}', summary: 'On an anonymized pilot store with 12,000 products.' },
  ],
  report: {
    test: { title: 'Test report: {name}', summary: '{n} new tests; coverage up {pct} points.' },
    fix: { title: 'Fix report: {name}', summary: 'Failing test first, then the fix; {n} suites pass.' },
    perf: { title: 'Perf report: {name}', summary: 'p95 from {p95} ms to {slo} ms in the load test.' },
    security: { title: 'Security fix report: {name}', summary: 'Patched and rescanned; no longer reproduces.' },
    refactor: { title: 'Refactor report: {name}', summary: '{n} contract tests unchanged; old path flagged off.' },
    docs: { title: 'Docs update: {name}', summary: 'Help article and API reference checked by support.' },
    cost: { title: 'Cost report: {name}', summary: 'Saves {pct}% a month with no change to p95.' },
    implement: { title: 'Build report: {name}', summary: 'Acceptance checks pass; {n} new tests for edge cases.' },
  },
};

export const releaseNotes = {
  new: ['Launched to all stores.', 'Beta for pilot stores.', 'Plus plans first.', 'Launched in all markets.'],
  improved: ['Faster on large stores.', 'Accessibility fixes.', 'Clearer error messages.', 'Now in the mobile app.', 'Lower cloud cost.', 'Better test coverage.', 'Audit log entries.', 'More languages.'],
  fixed: ['Race on concurrent updates.', 'Time zones in date filters.', 'Rounding on tax-inclusive totals.', 'Crash on empty lists.', 'Duplicate notifications.', 'Sorting with accented names.'],
};

export const incidents = [
  'Elevated 5xx errors for 42 minutes after a config change',
  'Slow responses during a traffic spike from a flash sale',
  'Queue backlog delayed processing for two hours',
  'Upstream provider outage degraded the service',
  'Memory leak caused repeated container restarts',
  'Database failover added 6 minutes of errors',
];
